// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProiectDRXTransports.Data;

#nullable disable

namespace ProiectDRXTransports.Migrations
{
    [DbContext(typeof(ProiectDRXTransportsContext))]
    partial class ProiectDRXTransportsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProiectDRXTransports.Models.DriverModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNr")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DriverModel");
                });

            modelBuilder.Entity("ProiectDRXTransports.Models.GateModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("LocationModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationModelId");

                    b.ToTable("GateModel");
                });

            modelBuilder.Entity("ProiectDRXTransports.Models.LocationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocationModel");
                });

            modelBuilder.Entity("ProiectDRXTransports.Models.TransportationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverModelId")
                        .HasColumnType("int");

                    b.Property<int>("LocationModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusTransport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DriverModelId");

                    b.HasIndex("LocationModelId");

                    b.ToTable("TransportationModel");
                });

            modelBuilder.Entity("ProiectDRXTransports.Models.TransportationScheduleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<TimeSpan>("DeliveryTime")
                        .HasColumnType("time");

                    b.Property<int>("GateModelId")
                        .HasColumnType("int");

                    b.Property<int>("TransportationModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GateModelId");

                    b.HasIndex("TransportationModelId");

                    b.ToTable("TransportationScheduleModel");
                });

            modelBuilder.Entity("ProiectDRXTransports.Models.GateModel", b =>
                {
                    b.HasOne("ProiectDRXTransports.Models.LocationModel", "LocationModel")
                        .WithMany()
                        .HasForeignKey("LocationModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocationModel");
                });

            modelBuilder.Entity("ProiectDRXTransports.Models.TransportationModel", b =>
                {
                    b.HasOne("ProiectDRXTransports.Models.DriverModel", "DriverModel")
                        .WithMany()
                        .HasForeignKey("DriverModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProiectDRXTransports.Models.LocationModel", "LocationModel")
                        .WithMany()
                        .HasForeignKey("LocationModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverModel");

                    b.Navigation("LocationModel");
                });

            modelBuilder.Entity("ProiectDRXTransports.Models.TransportationScheduleModel", b =>
                {
                    b.HasOne("ProiectDRXTransports.Models.GateModel", "GateModel")
                        .WithMany()
                        .HasForeignKey("GateModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProiectDRXTransports.Models.TransportationModel", "TransportationModel")
                        .WithMany()
                        .HasForeignKey("TransportationModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GateModel");

                    b.Navigation("TransportationModel");
                });
#pragma warning restore 612, 618
        }
    }
}
